//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testovi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termini
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termini()
        {
            this.Obavijesti = new HashSet<Obavijesti>();
            this.Rezervacije = new HashSet<Rezervacije>();
        }
    
        public int ID_termina { get; set; }
        public int instrukcija_id { get; set; }
        public string naziv_termina { get; set; }
        public System.DateTime vrijeme_termina { get; set; }
        public int trajanje { get; set; }
        public string mjesto_odrzavanja { get; set; }
        public int kapacitet_termina { get; set; }
    
        public virtual Instrukcije Instrukcije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obavijesti> Obavijesti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacije> Rezervacije { get; set; }
    }
}
