//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testovi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tip_instrukcija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tip_instrukcija()
        {
            this.Instrukcije = new HashSet<Instrukcije>();
        }
    
        public int ID_tip_instrukcije { get; set; }
        public string naziv_tipa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instrukcije> Instrukcije { get; set; }
    }
}
