//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAndLearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instruktori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instruktori()
        {
            this.Instrukcije = new HashSet<Instrukcije>();
            this.Poruke = new HashSet<Poruke>();
            this.Recenzije = new HashSet<Recenzije>();
        }
    
        public int ID_instruktora { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public string email { get; set; }
        public string mobitel { get; set; }
        public string mjesto { get; set; }
        public string ulica { get; set; }
        public string titula { get; set; }
        public string opis { get; set; }
        public byte[] slika { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instrukcije> Instrukcije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poruke> Poruke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzije> Recenzije { get; set; }
    }
}
